### PR TITLE
I18n update

### PR DESCRIPTION
**Pull request by KrzysztofMadejski**
I've:
- removed the hack I've mentioned in #50 by using mocks (CI should build properly now)
- removed translations that are defined in dependent plugins (report, archiver)

### CODE REVIEW

**Comment by KrzysztofMadejski** [comment]
Travis CI is failing with:
```
File "/home/travis/build/ckan/ckanext-qa/ckanext/qa/lib.py", line 9, in <module>
    from ckan.lib.celery_app import celery
File "/home/travis/build/ckan/ckanext-qa/ckan/ckan/lib/celery_app.py", line 18, in <module>
    raise ImportError(u'Only Celery version 3.x is supported.')
```

What can be done with that? That relates to ckan core. Somehow it didn't file on my setup and I have `celery==2.4.2` (but also CKAN 2.3 - maybe it's because of that). Anyway, at which point celery is installed? I guess here: https://github.com/ckan/ckanext-archiver/blob/master/requirements.txt (should there be many requirements file per CKAN version?) Shouldn't ckan require proper celery version?

**Comment by KrzysztofMadejski** [comment]
BTW: I've slipped also #44 in this PR.

**Comment by KrzysztofMadejski** [comment]
@davidread ready to be merged. There won't be any more i18n updates.

**Comment by davidread** [comment]
Upgrading celery is long overdue. I'd be v happy if you're happy to test a more recent version on ckanext-archiver & qa and we can change the suggested version.

**Comment by KrzysztofMadejski** [comment]
Will see if I have time to do it.

**Comment by KrzysztofMadejski** [comment]
Altough it's not crucial for me as I'm running older CKAN, so cannot promise aything. I've filed this as #52

**Pull request merged**
