### PR TITLE
Internationalization (i18n) and updated requirements

### PR DESCRIPTION
**Pull request by KrzysztofMadejski**
i18n ready to be pulled in. Requirements in setup.py are open-ended @davidread .

There is just one hack used for testing, which I have no idea how to overcome: https://github.com/ckan/ckan/issues/3491

### CODE REVIEW

**Comment by KrzysztofMadejski** [comment]
Ready to be merged! @davidread

**Comment by davidread** [comment]
Thanks @KrzysztofMadejski this is really valuable sorting out the translatability!

**Comment by KrzysztofMadejski** [comment]
One change that may affect you (I don't know if you seen that): I've changed in the templates "Publisher" to "Organization" as it's default CKAN term. You'll need to overwrite that in the application translation files if you want to keep "Publisher". 

BTW: See https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/blob/develop/ckanext/danepubliczne/i18n/aggregate_and_compile.sh for a script to aggregate `po` files from multiple plugins into one master translation file used by final application.

**Comment by davidread** [comment]
Yeah, I'm good with changing Publisher to Organization.

Perhaps you could you add a brief note about translation to the README, mentioning this script?

**Comment by KrzysztofMadejski** [comment]
Sure. I couldn't update this PR, so I've created a new one: https://github.com/ckan/ckanext-qa/pull/51 
It has more meaningful changes than just addition to README

**Pull request merged**
